// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMemoryDump(arg1) {
  return window['go']['main']['App']['CreateMemoryDump'](arg1);
}

export function DisconnectUser(arg1) {
  return window['go']['main']['App']['DisconnectUser'](arg1);
}

export function GetPerfExtra() {
  return window['go']['main']['App']['GetPerfExtra']();
}

export function GetProcessAffinity(arg1) {
  return window['go']['main']['App']['GetProcessAffinity'](arg1);
}

export function GetProcessNice(arg1) {
  return window['go']['main']['App']['GetProcessNice'](arg1);
}

export function GetProcessProps(arg1) {
  return window['go']['main']['App']['GetProcessProps'](arg1);
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function KillProcessRoot(arg1) {
  return window['go']['main']['App']['KillProcessRoot'](arg1);
}

export function KillProcessTree(arg1) {
  return window['go']['main']['App']['KillProcessTree'](arg1);
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListProcessesByUser(arg1) {
  return window['go']['main']['App']['ListProcessesByUser'](arg1);
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListStartupApps() {
  return window['go']['main']['App']['ListStartupApps']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function OpenProcessLocation(arg1) {
  return window['go']['main']['App']['OpenProcessLocation'](arg1);
}

export function OpenServiceStatus(arg1) {
  return window['go']['main']['App']['OpenServiceStatus'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function ServiceAction(arg1, arg2) {
  return window['go']['main']['App']['ServiceAction'](arg1, arg2);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetEfficiencyMode(arg1, arg2) {
  return window['go']['main']['App']['SetEfficiencyMode'](arg1, arg2);
}

export function SetProcessAffinity(arg1, arg2) {
  return window['go']['main']['App']['SetProcessAffinity'](arg1, arg2);
}

export function SetProcessNice(arg1, arg2) {
  return window['go']['main']['App']['SetProcessNice'](arg1, arg2);
}

export function SetStartupEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1, arg2);
}
