// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateMemoryDump(arg1:number):Promise<string>;

export function DisconnectUser(arg1:string):Promise<string>;

export function GetPerfExtra():Promise<main.PerfExtra>;

export function GetProcessAffinity(arg1:number):Promise<string>;

export function GetProcessNice(arg1:number):Promise<number>;

export function GetProcessProps(arg1:number):Promise<main.ProcessProps>;

export function GetSystemStats():Promise<main.SystemStats>;

export function KillProcess(arg1:number):Promise<string>;

export function KillProcessRoot(arg1:number):Promise<string>;

export function KillProcessTree(arg1:number):Promise<string>;

export function ListProcesses():Promise<Array<main.Process>>;

export function ListProcessesByUser(arg1:string):Promise<Array<main.Process>>;

export function ListServices():Promise<Array<main.ServiceRow>>;

export function ListStartupApps():Promise<Array<main.StartupApp>>;

export function ListUsers():Promise<Array<main.UserRow>>;

export function OpenProcessLocation(arg1:number):Promise<string>;

export function OpenServiceStatus(arg1:string):Promise<string>;

export function RunCommand(arg1:string):Promise<string>;

export function ServiceAction(arg1:string,arg2:string):Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetEfficiencyMode(arg1:number,arg2:boolean):Promise<string>;

export function SetProcessAffinity(arg1:number,arg2:string):Promise<string>;

export function SetProcessNice(arg1:number,arg2:number):Promise<string>;

export function SetStartupEnabled(arg1:string,arg2:boolean):Promise<string>;
